### ISSUE TITLE
所有连接点击时显示invalid rule

### ISSUE THREAD

**Issue by ShiJie137** [MatsuriDayo/NekoBoxForAndroid#104]
**描述问题**
所有连接点击时显示invalid rule，昨天能够正常使用，期间没有动过设置，订阅能够正常更新，尝试七八个订阅都是这样
设置trace重启软件后得到两个日志，一个为导出，一个为软件内

**日志**
trace导出日志

[NB4A 2204009564623868426.log](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/11302662/NB4A.2204009564623868426.log)

软件内日志：
2023/04/23 01:51:42 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:37)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:180)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:51:42 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:51:42 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:51:49 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:51:55 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:52:33 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 01:58:01 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 02:01:35 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:37)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:180)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 02:01:41 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 02:01:44 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

2023/04/23 02:01:51 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:206)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:145)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4518)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by ShiJie137** [comment]
感谢，问题已解决
