### ISSUE TITLE
正常使用时，更新订阅后无法选择节点

### ISSUE THREAD

**Issue by Ouyanglui** [MatsuriDayo/NekoBoxForAndroid#215]
**描述问题**

预期行为：
更新订阅后选择节点后应该正常使用，所有机场均不可使用。
实际行为：
选择节点后，出现“失败：invalid rule”
**如何复现**
点击节点就会出现该提示。

![Screenshot_20230701-200731__01.jpg](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/46159604/216ebb94-a13d-410c-bc45-27d0ff8320f7)

**日志**
2023/07/01 12:23:27 [Warning] [BaseService$Interface$onStartCommand$2] java.lang.Exception: invalid rule
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig(ConfigBuilder.kt:215)
	at io.nekohasekai.sagernet.fmt.ConfigBuilderKt.buildConfig$default(ConfigBuilder.kt:12)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.buildConfig(BoxInstance.kt:6)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.buildConfig(ProxyInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init$suspendImpl(BoxInstance.kt:79)
	at io.nekohasekai.sagernet.bg.proto.BoxInstance.init(BoxInstance.kt:1)
	at io.nekohasekai.sagernet.bg.proto.ProxyInstance.init(ProxyInstance.kt:59)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$onStartCommand$2.invokeSuspend(BaseService.kt:100)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:152)
	at kotlinx.coroutines.AbstractCoroutine.start$enumunboxing$(AbstractCoroutine.kt:85)
	at io.nekohasekai.sagernet.ktx.AsyncsKt.runOnMainDispatcher(Asyncs.kt:62)
	at io.nekohasekai.sagernet.bg.BaseService$Interface$DefaultImpls.onStartCommand(BaseService.kt:154)
	at io.nekohasekai.sagernet.bg.VpnService.onStartCommand(VpnService.kt:38)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4513)
	at android.app.ActivityThread.access$2200(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2131)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8010)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
如果有日志，请上传。请在文档内查看导出日志的详细步骤。

**Comment by Ouyanglui** [comment]
> 这是rule出现错误，比如选择了某个节点，但这个节点随后被删除。‘
> 
> 
> 在 https://github.com/MatsuriDayo/NekoBoxForAndroid/actions/runs/5431055876 版本后，此类问题由错误转化为警告，可以下载试用。

解决了，谢谢。之前都是重新下载再导入配置，这样选择节点就会失败。
