### ISSUE TITLE
BUG: 更新订阅时提示“x509: certificate signed by unknown authority”

### ISSUE THREAD

**Issue by rainin9** [MatsuriDayo/NekoBoxForAndroid#382]
## 描述问题

预期行为：正常更新订阅

实际行为：更新订阅时提示“x509: certificate signed by unknown authority”

## 如何复现
NekoBoxForAndroid 1.2.7

使用https://id9.cc/ 进行订阅转换，订阅转换后的URL更新时提示

> Get "https://sub.id9.cc/……": tls: failed to verify certificate: x509: certificate signed by unknown authority

使用手机浏览器Firefox Nightly和chrome均可正常访问订阅链接，无证书错误。

## 日志

````
[Warning] [GroupUpdater$Companion$executeUpdate$2] go.Universe$proxyerror: Get "https://sub.id9.cc/……": tls: failed to verify certificate: x509: certificate signed by unknown authority
 at libcore.Libcore$proxyHTTPRequest.execute(Native Method)
 at io.nekohasekai.sagernet.group.RawUpdater.doUpdate(RawUpdater.kt:18)
 at io.nekohasekai.sagernet.group.GroupUpdater$Companion$executeUpdate$2.invokeSuspend(GroupUpdater.kt:264)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
 at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
````

**Comment by Misaka-blog** [comment]
已成功复现。不过建议还是不使用订阅转换

**Comment by purofle** [comment]
订阅转换器自身证书问题，不进行解决。
