### ISSUE TITLE
BUG: the program crashes on vless configurations containing uTLS android

### ISSUE THREAD

**Issue by AlemSpika** [MatsuriDayo/NekoBoxForAndroid#505]
[profile_crash.txt](https://github.com/MatsuriDayo/NekoBoxForAndroid/files/13789531/profile_crash.txt)
## Describe the problem

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by AlemSpika** [comment]
2023/12/29 23:22:53 INFO[0000] sing-box started (0.00s)
2023/12/29 23:22:53 INFO[0000] outbound/vless[proxy]: outbound connection to detectportal.firefox.com:80
2023/12/29 23:22:53 INFO[0000] outbound/vless[proxy]: outbound connection to detectportal.firefox.com:80
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7cb590cee8]

goroutine 3 [running]:
github.com/sagernet/sing-box/common/tls.(*RealityClientConfig).ClientHandshake(0x40003a6810, {0x7cb5e05200, 0x4000320050}, {0x7cb5e0b908, 0x40003080a8})
	github.com/sagernet/sing-box@v1.0.0/common/tls/reality_client.go:145 +0x5d8
github.com/sagernet/sing/common/tls.ClientHandshake({0x7cb5e05200, 0x4000320050}, {0x7cb5e0b908, 0x40003080a8}, {0x7cb5e0ade0, 0x40003a6810})
	github.com/sagernet/sing@v0.2.17/common/tls/config.go:55 +0xec
github.com/sagernet/sing-box/common/tls.ClientHandshake({0x7cb5e051c8?, 0x40003040c0?}, {0x7cb5e0b908, 0x40003080a8}, {0x7cb5e0ade0, 0x40003a6810})
	github.com/sagernet/sing-box@v1.0.0/common/tls/client.go:45 +0x70
github.com/sagernet/sing-box/transport/v2raygrpclite.NewClient.func2({0x7cb5e051c8, 0x40003040c0}, {0x7cb512c598?, 0x7dc2a00f40?}, {0x400005dda8?, 0x7cb52bc89c?}, 0x4000304000?)
	github.com/sagernet/sing-box@v1.0.0/transport/v2raygrpclite/client.go:78 +0xa8
golang.org/x/net/http2.(*Transport).dialTLS(0x40003b0120?, {0x7cb5e051c8?, 0x40003040c0?}, {0x7cb512c598?, 0x4000302000?}, {0x400009e000?, 0x400005df38?}, 0x400005df28?)
	golang.org/x/net@v0.18.0/http2/transport.go:688 +0x1c0
golang.org/x/net/http2.(*Transport).dialClientConn(0x400005df48?, {0x7cb5e051c8, 0x40003040c0}, {0x400009e000, 0x1a}, 0x0?)
	golang.org/x/net@v0.18.0/http2/transport.go:665 +0x78
golang.org/x/net/http2.(*dialCall).dial(0x400003e040, {0x7cb5e051c8?, 0x40003040c0?}, {0x400009e000, 0x1a})
	golang.org/x/net@v0.18.0/http2/client_conn_pool.go:141 +0x40
created by golang.org/x/net/http2.(*clientConnPool).getStartDialLocked in goroutine 53
	golang.org/x/net@v0.18.0/http2/client_conn_pool.go:134 +0x1fc
