### ISSUE TITLE
BUG: 1.31崩溃

### ISSUE THREAD

**Issue by flin-ux** [MatsuriDayo/NekoBoxForAndroid#572]
## Describe the problem打开1.31版本，恢复备份会崩溃；
点击个别订阅组，也会崩溃。

Expected behavior:

Actual behavior:

## How to reproduce

Provide helpful screenshots, videos, text descriptions, subscription links, etc.

## log

If you have logs, please upload them. Please see the detailed steps for exporting logs in the documentation.

**Comment by purofle** [comment]
log pls

**Comment by flin-ux** [comment]
NekoBox for Andoird 1.3.1 (175) OSS
Date: 2024-03-04 13:06:43.245 UTC

OS_VERSION: 5.10.185-android12-9-00029-g00c7bec87c46-ab10751602
SDK_INT: 34
RELEASE: 14
ID: U1SQ34.53-33
DISPLAY: U1SQ34.53-33
INCREMENTAL: 2d7225-dc62e
SECURITY_PATCH: 2024-01-01
IS_DEBUGGABLE: 0
IS_EMULATOR: null
IS_TREBLE_ENABLED: true
TYPE: user
TAGS: release-keys

MANUFACTURER: motorola
BRAND: motorola
MODEL: XT2241-1
PRODUCT: eqs_cn
BOARD: eqs
HARDWARE: qcom
DEVICE: eqs
SUPPORTED_ABIS: arm64-v8a, armeabi-v7a, armeabi

Settings: 

mixedPort: 2080
portLocalDns: 6450
isAutoConnect: false
nightTheme: 0
serviceMode: vpn
tunImplementation: 2
mtu: 9000
speedInterval: 1000
profileTrafficStatistics: true
showDirectSpeed: true
logLevel: 0
trafficSniffing: 1
resolveDestination: false
mux: []
muxConcurrency: 8
remoteDns: https://dns.google/dns-query
directDns: local
allowAccess: false
connectionTestURL: http://cp.cloudflare.com/
acquireWakeLock: false
tcpKeepAliveInterval: 15
showGroupInNotification: true
alwaysShowAddress: true
meteredNetwork: true
bypassLan: true
rulesProvider: 2
globalAllowInsecure: true
domain_strategy_for_remote: prefer_ipv6
domain_strategy_for_direct: prefer_ipv6
domain_strategy_for_server: prefer_ipv6
enableFakeDns: true
enableDnsRouting: false
appendHttpProxy: true
enableClashAPI: true
appTLSVersion: 1.3
showBottomBar: true
allowInsecureOnRequest: true
ipv6Mode: 2
muxType: 2
proxyApps: true
bypassMode: false
appTheme: 7
bypassLanInCore: true
individual: com.aurora.store.nightly
com.microsoft.bing
com.yandex.browser.beta
org.fdroid.fdroid
com.google.android.inputmethod.latin
com.google.android.gm
com.android.vending
com.google.android.gms
com.google.android.gsf
com.imgur.mobile
com.issuu.android.app
com.github.libretube
com.mgoogle.android.gms
cn.mujiankeji.mbrowser
xyz.nextalone.nagram
InfinityLoop1309.NewPipeEnhanced
ussr.razar.youtube_dl
com.quora.android
yt.rvx.noname.exe
ytm.rvx.noname.exe
com.reddit.frontpage
com.artxdev.songtube
com.google.android.apps.translate
com.tumblr
com.google.android.apps.googlevoice
org.wikipedia
com.twitter.android
com.microsoft.copilot
yacdURL: http://127.0.0.1:9090/ui
profileCurrent: 96070
profileId: 0
profileGroup: 119

Logcat: 

--------- beginning of system
03-04 21:05:56.437 25716 25716 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
03-04 21:05:56.437 25716 25716 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
03-04 21:05:56.437 25716 25716 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
03-04 21:05:56.437 25716 25716 D ViewRootImpl:   bhv=DEFAULT
03-04 21:05:56.437 25716 25716 D ViewRootImpl:   fitSides=} by setView
--------- beginning of main
03-04 21:06:03.668 25880 25880 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10730; state: ENABLED
03-04 21:06:03.678 25880 25880 W ResourcesCompat: Failed to inflate ColorStateList, leaving it to the framework
03-04 21:06:03.678 25880 25880 W ResourcesCompat: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040275 a=-1}, theme={InheritanceMap=[id=0x7f140287moe.nb4a:style/Theme.SagerNet.Blue, id=0x7f140284moe.nb4a:style/Theme.SagerNet, id=0x7f140267moe.nb4a:style/Theme.MaterialComponents.DayNight.NoActionBar, id=0x7f140282moe.nb4a:style/Theme.MaterialComponents.NoActionBar, id=0x7f140255moe.nb4a:style/Theme.MaterialComponents, id=0x7f140060moe.nb4a:style/Base.Theme.MaterialComponents, id=0x7f1400a0moe.nb4a:style/Base.V21.Theme.MaterialComponents, id=0x7f14008cmoe.nb4a:style/Base.V14.Theme.MaterialComponents, id=0x7f14008dmoe.nb4a:style/Base.V14.Theme.MaterialComponents.Bridge, id=0x7f140135moe.nb4a:style/Platform.MaterialComponents, id=0x7f14021emoe.nb4a:style/Theme.AppCompat, id=0x7f14004amoe.nb4a:style/Base.Theme.AppCompat, id=0x7f1400b3moe.nb4a:style/Base.V28.Theme.AppCompat, id=0x7f1400b0moe.nb4a:style/Base.V26.Theme.AppCompat, id=0x7f1400aamoe.nb4a:style/Base.V23.Theme.AppCompat, id=0x7f1400a8moe.nb4a:style/Base.V22.Theme.AppCompat, id=0x7f14009cmoe.nb4a:style/Base.V21.Theme.AppCompat, id=0x7f1400b5moe.nb4a:style/Base.V7.Theme.AppCompat, id=0x7f140133moe.nb4a:style/Platform.AppCompat, id=0x7f14013emoe.nb4a:style/Platform.V25.AppCompat, id=0x103022eandroid:style/Theme.Material.NoActionBar, id=0x1030224android:style/Theme.Material, id=0x1030005android:style/Theme], Themes=[moe.nb4a:style/Theme.SagerNet.Blue, forced, moe.nb4a:style/Theme.Start, forced, moe.nb4a:style/Theme.AppCompat.Empty, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.content.res.TypedArray.getColor(TypedArray.java:529)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXmlInner(ColorStateListInflaterCompat.java:147)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:18)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:123)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at com.google.android.material.resources.MaterialResources.getColorStateList(MaterialResources.java:7)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at com.google.android.material.navigation.NavigationView.<init>(NavigationView.java:359)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.createView(LayoutInflater.java:866)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1018)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:694)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at io.nekohasekai.sagernet.databinding.LayoutMainBinding.inflate(LayoutMainBinding.java:2)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at io.nekohasekai.sagernet.databinding.LayoutMainBinding.inflate(LayoutMainBinding.java:1)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at io.nekohasekai.sagernet.ui.MainActivity.onCreate(MainActivity.kt:18)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.Activity.performCreate(Activity.java:8732)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.Activity.performCreate(Activity.java:8710)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3879)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4041)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2547)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.os.Handler.dispatchMessage(Handler.java:111)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.os.Looper.loopOnce(Looper.java:242)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.os.Looper.loop(Looper.java:362)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at android.app.ActivityThread.main(ActivityThread.java:8393)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at java.lang.reflect.Method.invoke(Native Method)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
03-04 21:06:03.678 25880 25880 W ResourcesCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
03-04 21:06:03.681 25880 25880 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
03-04 21:06:03.681 25880 25880 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
03-04 21:06:03.699 25880 25880 D CompatibilityChangeReporter: Compat change id reported: 171228096; UID 10730; state: ENABLED
03-04 21:06:03.700 25880 25880 W TabLayout: MODE_SCROLLABLE + GRAVITY_FILL is not supported, GRAVITY_START will be used instead
03-04 21:06:03.733 25880 25880 D CompatibilityChangeReporter: Compat change id reported: 237531167; UID 10730; state: DISABLED
03-04 21:06:03.738 25880 25880 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
03-04 21:06:03.738 25880 25880 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
03-04 21:06:03.738 25880 25880 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
03-04 21:06:03.738 25880 25880 D ViewRootImpl:   bhv=DEFAULT
03-04 21:06:03.738 25880 25880 D ViewRootImpl:   fitSides=} by setView
03-04 21:06:03.758 25880 25880 D AutofillManager: view not autofillable - not passing ime action check
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: QUALCOMM build                   : dad4038ba6, If56d4a5bb8
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Build Date                       : 07/28/23
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.36.08.24
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Local Branch                     : 
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.1.0.11.00.00.766.892
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Remote Branch                    : NONE
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Build Config                     : S P 12.1.1 AArch64
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
03-04 21:06:03.779 25880 25923 I AdrenoGLES-0: Driver Version                   : 0615.74
03-04 21:06:03.782 25880 25923 I AdrenoGLES-0: PFP: 0x01730158, ME: 0x00000000
03-04 21:06:03.805 25880 25923 I OpenGLRenderer: setGrContext nullptr-->validptr
03-04 21:06:03.806 25880 25923 E OpenGLRenderer: Unable to match the desired swap behavior.
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: java.lang.StringIndexOutOfBoundsException: length=64; regionStart=0; regionLength=-1495816148
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at java.lang.StringFactory.newStringFromChars(StringFactory.java:122)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at com.esotericsoftware.kryo.io.ByteBufferInput.readString(ByteBufferInput.java:479)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.fmt.AbstractBean.deserializeFromBuffer(AbstractBean.java:19)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.fmt.KryoConverters.deserialize(KryoConverters.java:13)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.fmt.KryoConverters.trojanDeserialize(KryoConverters.java:14)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.database.ProxyEntity_Dao_Impl.getByGroup(ProxyEntity_Dao_Impl.java:377)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.ui.ConfigurationFragment$GroupFragment$ConfigurationAdapter.reloadProfiles(ConfigurationFragment.kt:22)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at io.nekohasekai.sagernet.ui.ConfigurationFragment$GroupFragment$onResume$2.invokeSuspend(ConfigurationFragment.kt:16)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:6)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:79)
03-04 21:06:03.912 25880 25903 E Thread[DefaultDispatcher-worker-1,5,main]: 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2bbc35f, Dispatchers.Default]
03-04 21:06:03.968 26196 26196 I oe.nb4a:phoenix: Using CollectorTypeCMC GC.
03-04 21:06:03.971 26196 26196 E oe.nb4a:phoenix: Not starting debugger since process cannot load the jdwp agent.
03-04 21:06:04.012 26196 26196 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10730; state: ENABLED
03-04 21:06:04.012 26196 26196 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10730; state: DISABLED
03-04 21:06:04.020 26196 26196 D nativeloader: Configuring clns-4 for other apk /data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/lib/arm64:/data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/moe.nb4a
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment: Currently set values for:
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment: ANGLE GameManagerService for moe.nb4a: false
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment: moe.nb4a is not listed in per-application setting
03-04 21:06:04.028 26196 26196 V GraphicsEnvironment: Updatable production driver is not supported on the device.
03-04 21:06:04.040 26196 26196 W oe.nb4a:phoenix: type=1400 audit(0.0:110586): avc:  denied  { read } for  name="tcp" dev="proc" ino=4026532037 scontext=u:r:untrusted_app_32:s0:c218,c258,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=moe.nb4a
03-04 21:06:04.050 26196 26196 W oe.nb4a:phoenix: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
03-04 21:06:04.050 26196 26196 W oe.nb4a:phoenix: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
03-04 21:06:04.051 26196 26196 W oe.nb4a:phoenix: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
03-04 21:06:04.062 26196 26196 I Typeface: updateThemeFont new=Rookery-Regular;old=sans-serif;new=moto_time;old=
03-04 21:06:04.073 26196 26196 I Process : Sending signal. PID: 25880 SIG: 9
03-04 21:06:04.084 26196 26196 I oe.nb4a:phoenix: System.exit called, status: 0
03-04 21:06:04.084 26196 26196 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
03-04 21:06:04.175 26248 26248 I moe.nb4a: Using CollectorTypeCMC GC.
03-04 21:06:04.177 26248 26248 E moe.nb4a: Not starting debugger since process cannot load the jdwp agent.
03-04 21:06:04.191 26248 26248 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10730; state: ENABLED
03-04 21:06:04.192 26248 26248 D CompatibilityChangeReporter: Compat change id reported: 242716250; UID 10730; state: DISABLED
03-04 21:06:04.199 26248 26248 D nativeloader: Configuring clns-4 for other apk /data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/base.apk. target_sdk_version=33, uses_libraries=, library_path=/data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/lib/arm64:/data/app/~~RxFpR8k9izYZJqJRA3pDSQ==/moe.nb4a-rWqPIk3Whgif-F0zD-OXsg==/base.apk!/lib/arm64-v8a, permitted_path=/data:/mnt/expand:/data/user/0/moe.nb4a
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment: Currently set values for:
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment:   angle_gl_driver_selection_pkgs=[]
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment:   angle_gl_driver_selection_values=[]
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment: ANGLE GameManagerService for moe.nb4a: false
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment: moe.nb4a is not listed in per-application setting
03-04 21:06:04.206 26248 26248 V GraphicsEnvironment: Updatable production driver is not supported on the device.
03-04 21:06:04.220 26248 26248 W moe.nb4a: type=1400 audit(0.0:110587): avc:  denied  { read } for  name="tcp" dev="proc" ino=4026532037 scontext=u:r:untrusted_app_32:s0:c218,c258,c512,c768 tcontext=u:object_r:proc_net_tcp_udp:s0 tclass=file permissive=0 app=moe.nb4a
03-04 21:06:04.229 26248 26248 W moe.nb4a: Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
03-04 21:06:04.229 26248 26248 W moe.nb4a: Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
03-04 21:06:04.229 26248 26248 W moe.nb4a: Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
03-04 21:06:04.242 26248 26248 I Typeface: updateThemeFont new=Rookery-Regular;old=sans-serif;new=moto_time;old=
03-04 21:06:04.248 26248 26248 D AppCompatDelegate: Checking for metadata for AppLocalesMetadataHolderService : Service not found
03-04 21:06:12.801 26248 26248 D CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10730; state: ENABLED
03-04 21:06:12.813 26248 26248 W ResourcesCompat: Failed to inflate ColorStateList, leaving it to the framework
03-04 21:06:12.813 26248 26248 W ResourcesCompat: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 0: TypedValue{t=0x2/d=0x7f040275 a=-1}, theme={InheritanceMap=[id=0x7f140287moe.nb4a:style/Theme.SagerNet.Blue, id=0x7f140284moe.nb4a:style/Theme.SagerNet, id=0x7f140267moe.nb4a:style/Theme.MaterialComponents.DayNight.NoActionBar, id=0x7f140282moe.nb4a:style/Theme.MaterialComponents.NoActionBar, id=0x7f140255moe.nb4a:style/Theme.MaterialComponents, id=0x7f140060moe.nb4a:style/Base.Theme.MaterialComponents, id=0x7f1400a0moe.nb4a:style/Base.V21.Theme.MaterialComponents, id=0x7f14008cmoe.nb4a:style/Base.V14.Theme.MaterialComponents, id=0x7f14008dmoe.nb4a:style/Base.V14.Theme.MaterialComponents.Bridge, id=0x7f140135moe.nb4a:style/Platform.MaterialComponents, id=0x7f14021emoe.nb4a:style/Theme.AppCompat, id=0x7f14004

**Comment by flin-ux** [comment]
已经解决了。把加载出来所有节点删除，仅保留订阅、 app设置备份，然后完全卸载，安装1.31后恢复备份，重新更新订阅，加载节点。

**Comment by purofle** [comment]
话说之前用的是什么版本？

**Comment by flin-ux** [comment]
> 话说之前用的是什么版本？

1.29
