### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by re7gog** [MatsuriDayo/NekoBoxForAndroid#606]
Crashes in background

Expected behavior:
Work in backround

Actual behavior:
Crashes and disconnects after a period of time

## How to reproduce

I'm using Hysteria 2 or Vless Reality with custom config for automatic bypassing or proxing websites by geosite and geoip

## log

2024/03/15 17:28:47 [Debug] [TrafficLooper] traffic count proxy to 8
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x705d59d954]

goroutine 17 [running, locked to thread]:
libcore.(*BoxInstance).Sleep(0x40003683c0)
	libcore@v0.0.0-00010101000000-000000000000/box.go:151 +0x24
main.proxylibcore_BoxInstance_Sleep(0xffffff01?)
	gobind/gobind/go_libcoremain.go:128 +0x38

**Comment by re7gog** [comment]
Version 1.2.9 works fine
