### ISSUE TITLE
BUG: 锁屏后中断连接

### ISSUE THREAD

**Issue by Youxikong** [MatsuriDayo/NekoBoxForAndroid#697]
## 描述问题

预期行为：锁屏后保持连接

实际行为：锁屏后连接中断。

## 如何复现

系统为Android 14，启动应用，打开VPN，回到桌面，锁屏。数分钟后解锁手机，状态栏VPN图标消失。已允许无限制使用电池电量。

## 日志

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7931db0954]

goroutine 17 [running, locked to thread]:
libcore.(*BoxInstance).Sleep(0x400131b400)
	libcore@v0.0.0-00010101000000-000000000000/box.go:151 +0x24
main.proxylibcore_BoxInstance_Sleep(0xffffff01?)
	gobind/gobind/go_libcoremain.go:128 +0x38
```

**Comment by 2378** [comment]
原版14 ，电量选线里 有选项：用不自动休眠的app  

别说锁屏，一天一夜都不会断链

**Comment by sniper54** [comment]
> 原版14 ，电量选线里 有选项：永不自动休眠的app
> 
> 别说锁屏，一天一夜都不会断链

![Screenshot_20240617-104306](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/25277487/db1771a8-b52a-4dca-baf6-0a7b0246be9d)
来来来 你看看哪里有选项，pixel ，14

**Comment by 2378** [comment]
在 2024年6月17日週一 10:44，sniper54 ***@***.***> 寫道：

**Comment by 2378** [comment]
![Screenshot_20240617_111653_Device care](https://github.com/MatsuriDayo/NekoBoxForAndroid/assets/24506320/f9193c72-3c2e-4c75-8a1c-912dd9fd48be)
![Uploading Screenshot_20240617_112149_Device care.jpg…]()

**Comment by Youxikong** [comment]
原版14（笑🤣

**Comment by 2378** [comment]
港行三星S23也许不算100%原版，但从没断过 

鬼知道你是什么水货18手pixel 💩

锁个屏都能断 😱， 就算国行机也没见有人说锁屏断线的 😳

**Comment by Youxikong** [comment]
🤣我这是Pixel OS，第三方ROM。再说你这三星有什么资格指着Pixel手机说自己是原版Android 14的，Lineage OS血统都比你纯正。

**Comment by Youxikong** [comment]
我发issue，是因为锁屏时会崩溃，日志报错，有错误内存地址或空指针，特来反馈下，希望维护者提供一个解决方案。你自己机圈矛盾别带我。

**Comment by 2378** [comment]
谁圈矛盾，大家都看着，血统论都搬出来了，呵呵

**Comment by sniper54** [comment]
我是自己海外买的Pixel7 Pro 512G 无锁

系统是原生14，没刷第三方系统

楼主说的问题，我的P7P上100%复现

我目前退回了1.30正常了

手机系统版本是最新的AP2A.240605.024

原生系统没有你三星系统的那个选项

**Comment by 2378** [comment]
@sniper54   永不自动休眠的app  允许无限制使用电池电量
在中文语境下，基本可以理解成同一功能

**Comment by sniper54** [comment]
但是勾选了也断

**Comment by 2378** [comment]
@sniper54  断~ 

说好听点 可能是因为 Pixel 血统纯正吧

说难听点  不就是HTC换个标吗 

Pixel 真那么好 全美市占率不到5% 而三星30% 😱

**Comment by Youxikong** [comment]
所以你装的是1.3.1版本吗，有复现出这个错误吗？

**Comment by sniper54** [comment]
> 所以你装的是1.3.1版本吗，有复现出这个错误吗？

我装的1.3.1断，改回1.3.0正常

**Comment by sniper54** [comment]
> @sniper54 断~
> 
> 说好听点 可能是因为 Pixel 血统纯正吧
> 
> 说难听点 不就是HTC换个标吗
> 
> Pixel 真那么好 全美市占率不到5% 而三星30% 😱

建议不要上升到品牌评判，就故障论故障

**Comment by jaoyina** [comment]
我还在1.29，没这个问题。

**Comment by bidabrain** [comment]
> 所以你装的是1.3.1版本吗，有复现出这个错误吗？

同样问题，我手机是one UI 6.1。 安装1.3.1以后出现问题

**Comment by Youxikong** [comment]
看来是1.3.1有问题。

**Comment by ilaotan** [comment]
早回退1.2.9了  beta版不折腾了
