### ISSUE TITLE
BUG: Unexpected terminating presumably when phone sleeping.  After i turn on the screen i see an error message

### ISSUE THREAD

**Issue by kashtanoff** [MatsuriDayo/NekoBoxForAndroid#731]
NB4A-1.3.1-arm64-v8a.apk

## Describe the problem

Unexpected terminating presumably when phone sleeping.  After i turn on the screen i see an error message

```
Something went wrong with NekoBox

NekoBox closed because this app has a bug.

Try updating this app after its developer
provides a fix for this error.
```

![photo_2024-08-07_12-03-28](https://github.com/user-attachments/assets/1566f79f-0138-4750-ba57-618a99764a03)

## log

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b9f597954]

goroutine 17 [running, locked to thread]:
libcore.(*BoxInstance).Sleep(0x4000192900)
 libcore@v0.0.0-00010101
000000-000000000000/box.go:151 +0x24
main.proxylibcore_BoxInstance_Sleep(0xffffff01?)
 gobind/gobind/go_libcoremain.go:128 +0x38
```

[nekobox_backup_Aug 7, 2024 12_04_39.json](https://github.com/user-attachments/files/16521080/nekobox_backup_Aug.7.2024.12_04_39.json)

**Comment by oklookat** [comment]
Same on Pixel 6a, Android 14.

[NB4A 7030969816048114876.log](https://github.com/user-attachments/files/16573393/NB4A.7030969816048114876.log)

**Comment by kashtanoff** [comment]
I use 1.2.9 for fix this problem

**Comment by KweezyCode** [comment]
same issue in 1.3.1
